name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-ci:
    name: 'Terraform CI & Security Scans'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: env/dev

    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Gitleaks Secret Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha || 'HEAD' }}
          extra_args: --only-verified

      - name: Trivy IaC Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "latest"

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact

      - name: Infracost Breakdown
        run: infracost breakdown --path .
